[build]
  command = "npm run generate" # Comando para generar los archivos estáticos
  publish = "dist"             # Directorio donde están los archivos generados

[build.environment]
  NODE_VERSION = "21.6.1"
  NODE_OPTIONS = "--max-old-space-size=8192"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true                 # Asegura que todas las rutas redirijan correctamente
